company = {
	teams: [
		{
			students: [
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
			],
			year: "2022-t2",
			teamId: "3535",
			teamName: "Team name",
			description: null,
			prototypeLink: null,
			mentors: null,
		},
		{
			students: [
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
			],
			year: "2022-t2",
			teamId: "3535",
			teamName: "Team name",
			description: null,
			prototypeLink: null,
			mentors: null,
		},
		{
			students: [
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
			],
			year: "2022-t2",
			teamId: "3535",
			teamName: "Team name",
			description: null,
			prototypeLink: null,
			mentors: null,
		},
		{
			students: [
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
			],
			year: "2022-t2",
			teamId: "3535",
			teamName: "Team name",
			description: null,
			prototypeLink: null,
			mentors: null,
		},
		{
			students: [
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
			],
			year: "2022-t2",
			teamId: "3535",
			teamName: "Team name",
			description: null,
			prototypeLink: null,
			mentors: null,
		},
		{
			students: [
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
			],
			year: "2022-t2",
			teamId: "3535",
			teamName: "Team name",
			description: null,
			prototypeLink: null,
			mentors: null,
		},
		{
			students: [
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
			],
			year: "2022-t2",
			teamId: "3535",
			teamName: "Team name",
			description: null,
			prototypeLink: null,
			mentors: null,
		},
		{
			students: [
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
			],
			year: "2022-t2",
			teamId: "3535",
			teamName: "Team name",
			description: null,
			prototypeLink: null,
			mentors: null,
		},
		{
			students: [
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
				{
					studentId: "535353535",
					fullName: "Person Personson",
					LinkedInProfile: "Linkedin link",
					displayPicture: null,
					role: "developer",
					areaOfSpecialisation: "yes",
					remarkableAchievements: "this is an achievement",
					teamId: "3535",
				},
			],
			year: "2022-t2",
			teamId: "3535",
			teamName: "Team name",
			description: null,
			prototypeLink: null,
			mentors: null,
		},
	],
};

const year = document.getElementById("year");
year.innerHTML = "2022-t2";

const timeline = document.getElementById("timeline-teams");
let HTML = [];
for (let index = 0; index < company.teams.length; index++) {
	HTML[index] =
		"<div class='card shadow-sm rounded col-l-3 col-md-4 col-sm-12 p-5 m-3'><h4 class='font-weight-bold text-primary'>" +
		company.teams[index].teamName +
		"</h4><button class='btn btn-light btn-outline-primary mt-5'>View details</button></div>";
}
timeline.innerHTML = HTML.join("");
